### ISSUE TITLE
After adding deliverable, list of deliverables does not update

### ISSUE THREAD

**Issue by kguthrie** [skuretski/cassiopeiaFront#17]
After adding a deliverable, a page refresh is required to display the new deliverable. Add Deliverable should behave like Add Project, where added item is immediately visible to the user.

**Comment by skuretski** [comment]
Fixed: ProjectView  deliverable navtabs > tabList was receiving props of ProjectViewData. Changed to tabList to filtering deliverables so reducer would change state.
