### ISSUE TITLE
TypeError: this.props.deliverables[this.props.match.params.deliv_id] is undefined

### ISSUE THREAD

**Issue by kguthrie** [skuretski/cassiopeiaFront#20]
Occasionally when refreshing a Task View page, I'll get this error in console:

```TypeError: this.props.deliverables[this.props.match.params.deliv_id] is undefined```

The line of code throwing the error is in the ADD_TASK_FORM modal section of TaskView.js.

I'm wondering if in TaskView.js, the this.state.loading Boolean value is being set to false before the setTaskViewData action-creator/reducer combo actually gets the projects to to the application state.

I'm unable to reproduce it reliably, which is what makes me think it's some sort of race condition between the getTaskViewData promise resolving and the setTaskVewData reducer returning data.

**Comment by skuretski** [comment]
Fixed: missing Else block for conditional rendering therefore it was racing depending on props.
```javascript        
if (this.state.loading === true) {
    return(
        <div className="text-center load-spinner" />
     );
}
//If project ID, deliverable ID, or task ID do not exist, redirect to 404
    else if(!projects[project_id] || !deliverables[deliv_id] || !tasks[task_id]){
        history.push("/404");
            return(
                <div></div>
            );
//If project does not have that specified deliverable, redirect to 404
    } else if(!(this.getProjectDeliverables(project_id, deliverables))[deliv_id]){
        history.push("/404");
            return(
                <div></div>
            );
//If deliverable does not have specified task, redirect to 404
    } else if(!(this.getDeliverableTasks(deliv_id, tasks))[task_id]){
        history.push("/404");
            return(
                <div></div>
            );
    }
//Else, render TaskViewData 
    else { 
        return( ... ); 
    } 
```
