### ISSUE TITLE
Auth: Research authentication options

### ISSUE THREAD

**Issue by kguthrie** [skuretski/cassiopeiaFront#9]

**Comment by skuretski** [comment]
- Passport Google OAuth 2.0 
[Github passport-google-oauth2](https://github.com/mstade/passport-google-oauth2)
[npm passport-goolge-oauth-2](https://www.npmjs.com/package/passport-google-oauth-2)

**Comment by kguthrie** [comment]
Everyone ready to start on this?

**Comment by skuretski** [comment]
No.
